pipeline:
  backend:
    image: ubuntu
    commands:
      - pwd
      - ps axuf
      - env | sort
  frontend:
    image: imma/ubuntu
    commands:
      - uname -a
      - id -a
      - cat .drone.yml
