pipeline:
- backend:
    image: ubuntu
    commands:
      - pwd
      - ps axuf
      - env | sort
- frontend:
    image: ubuntu
    commands:
      - uname -a
      - id -a
      - cat .drone.yml
      - echo hello chaz
