#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  source "$shome/script/profile" || return 1

  app list | sed "s#^#$APP_PATH/#" | runmany "$@"
}

source sub "$0" "$@"
