#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  source "$shome/script/profile" || return 1

  local pth_profile
  for pth_profile in $(app runmany 'ls -d $1/script/profile 2>&- || true'); do
    source "$pth_profile"
  done
}

source sub "$0" "$@"
