#!/usr/bin/env bash

function main {
  local phome="$(pwd)"
  local nm_pack="$1"; shift

  local tmp_cache="$(mktemp -d -t XXXXXX)"
  local tmp_env="$(mktemp -d -t XXXXXX)"

  cd "$phome"
  exec "app-compile-${nm_pack}" "$phome" "$tmp_cache" "$tmp_env" "$@"
}

main "$@"
