#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  source "$shome/script/profile" || return 1

  source app_clone

  block_walker clone:need_clone "$@"
}

source sub "$0" "$@"
