#!/usr/bin/env bash

function main {
  cat <<"__EOF"
#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"
}

source sub "$BASH_SOURCE" "$@"
__EOF
}

source sub "$0" "$@"
