#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local nm_package="$1"; shift
  case "$nm_package" in
    http*)
     local tmp_package="$(mktemp -t XXXXXX)"
     curl -sS -L -o "$tmp_package" "$nm_package"
      mv -f "$tmp_package" "$tmp_package.pkg"
      nm_package="$tmp_package.pkg"
      ;;
  esac
  local pth_hd="${1:-/Volumes/Macintosh HD}"

  case "$(uname -s)" in
    Darwin)
     sudo installer -package "$nm_package" -target "$pth_hd"
     ;;
  esac
}

source sub "$0" "$@"
