#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local url_package="$1"; shift
  local pth_hd="${1:-/Volumes/Macintosh HD}"
  local nm_package=
  case "$url_package" in
    http*)
      local fnm_packe="$(basename "$url_package")"
      cache curl "$fnm_package" "$url_package" -sS -L
      nm_package="${BASEBOX_CACHE}/curl/$fnm_package"
      ;;
    *)
      nm_package="$url_package"
  esac

  case "$(uname -s)" in
    Darwin)
     sudo installer -package "$nm_package" -target "$pth_hd"
     ;;
  esac
}

source sub "$0" "$@"
