#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local url_dmg="$1"; shift
  local nm_volume
  if [[ "$#" -gt 0 ]]; then
    nm_volume="$1"; shift
  fi
  local nm_package
  if [[ "$#" -gt 0 ]]; then
    nm_package="$1"; shift
  fi

  case "$(uname -s)" in
    Darwin)
      local fnm_dmg="$(basename "$url_dmg")"
      cache curl "$fnm_dmg" "$url_dmg" -sS -L
      hdiutil attach "${BASEBOX_CACHE}/curl/$fnm_dmg"
      trap "$(printf "hdiutil detach '%q'" "/Volumes/$nm_volume")" EXIT

      if [[ -n "$nm_package" ]]; then
        app compile pkg "/Volumes/$nm_volume/$nm_package"
      fi
      ;;
  esac
}

source sub "$0" "$@"
