#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  source "$shome/script/profile" || return 1

  source app_require

  block_walker require
  exec "$@"
}

source sub "$0" "$@"
