#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  source "$shome/script/profile" || return 1

  source app_bootstrap

  block_walker bootstrap "$@"
}

source sub "$0" "$@"
