#!/usr/bin/env bash

function bootstrap_block {
  if [[ -x "script/bootstrap" ]]; then
    debug echo INFO "$(pwd)/script/bootstrap" 1>&2
    #"script/bootstrap"
  fi
}

function bootstrap_in {
  local nm_project="$1"; shift

  pushd "$nm_project" 1>&-
  into_blockfile bootstrap
  bootstrap_block || fl_error=1
  popd 1>&-
}

function bootstrap {
  source "$APP_PATH/app/script/profile" || return 1
  source "$APP_PATH/jq/script/profile" || return 1
  block_walker "$FUNCNAME" "$@"
}
