#!/usr/bin/env bash

function list_block {
  local nm_block="${PWD##*/}"
  if [[ -f .app-name ]]; then
    read nm_block < .app-name
  fi

  local a="_list_${nm_block//-/_}"
  if [[ -z "${!a:-}" ]]; then
    read -r $a <<< 1
    export $a
    echo "$nm_block"
  fi
}

function list_in {
  local nm_project="$1"; shift

  pushd "$nm_project" >/dev/null
  into_blockfile list
  list_block || fl_error=1
  popd >/dev/null
}
