#!/usr/bin/env bash

function mark_source {
  local pth_profile="$1"; shift
  debug echo INFO "$pth_profile" 1>&2
}

function source_pre {
  local pth_profiled
  for pth_profiled in $(set +f; echo .profile.d/*.pre); do
    if [[ -f "$pth_profiled" ]]; then
      mark_source "$PWD/$pth_profiled"
      source "$pth_profiled"
    fi
  done
}

function source_profile {
  local nm_block=
  if [[ -f .app-name ]]; then
    nm_block="$(cat .app-name)"
  else
    nm_block="${PWD##*/}"
  fi

  if [[ -r "script/"profile ]]; then
    if eval test -z '${'"_require_${nm_block}"':-}'; then
      mark_source "$PWD/script/profile"
      eval "_require_${nm_block}=1"
      source "script/profile"
    fi
  else
    echo "WARNING: script/profile not found in $PWD" 1>&2
  fi
}

function source_post {
  local pth_profiled
  for pth_profiled in $(set +f; echo .profile.d/*.post); do
    if [[ -f "$pth_profiled" ]]; then
      mark_source "$PWD/$pth_profiled"
      source "$pth_profiled"
    fi
  done
}

function require_in {
  local nm_project="$1"; shift

  pushd "$nm_project" >/dev/null
  source_pre || fl_error=1
  into_blockfile require
  source_profile || fl_error=1
  source_post || fl_error=1
  popd >/dev/null
}

function require {
  block_walker "$FUNCNAME" "$@"
}
