#!/usr/bin/env bash

function bootstrap_stale {
  if [[ ! -x script/stale ]]; then
    return 0
  fi
  
  ${NOOP:+echo INFO $(pwd) }script/stale
}

function bootstrap_block {
  local nm_block="$(cat .app-name 2>&- || basename "$(pwd)")"

  local fl_error=0

  source_pre || fl_error=1

  if [[ -x "script/bootstrap" ]]; then
    debug echo INFO "$(pwd)/script/bootstrap" 1>&2
    if eval test -z '${'"_bootstrap_${nm_block}"':-}'; then
      if bootstrap_stale; then
        if ${NOOP:+echo INFO $(pwd) }script/bootstrap; then
          eval export "_bootstrap_${nm_block}=1"
        else
          fl_error=1
        fi
      fi
    fi
  fi
  
  if [[ "$fl_error" == 0 ]]; then
    source_profile || fl_error=1
    source_post || fl_error=1
  fi

  return $fl_error
}

function bootstrap_in {
  local nm_project="$1"; shift

  pushd "$nm_project" >/dev/null
  into_blockfile bootstrap
  bootstrap_block || fl_error=1
  popd >/dev/null
}
