#!/usr/bin/env bash

function need_clone {
  local nm_block="$1"; shift

  local url_git
  for url_git in $(site-map "$nm_block"); do
    if git clone "$url_git" "$APP_PATH/$nm_block"; then
      (cd "$APP_PATH/$nm_block" && app clone)
      break
    fi
  done
}

function clone_block {
  local nm_block="$(cat .app-name 2>&- || basename "$(pwd)")"

  local a="_clone_${nm_block//-/_}"
  if [[ -z "${!a:-}" ]]; then
    read -r $a <<< 1
    export $a
    echo "$nm_block"
  fi
}

function clone_in {
  local nm_project="$1"; shift

  pushd "$nm_project" >/dev/null
  into_blockfile clone:need_clone
  clone_block || fl_error=1
  popd >/dev/null
}
