#!/usr/bin/env bash

function bootstrap_block {
  local fl_error=0
  if [[ -x "script/bootstrap" ]]; then
    debug echo INFO "$(pwd)/script/bootstrap" 1>&2
    source_pre || fl_error=1
    if eval test -z '${'"_bootstrap_$(basename "$(pwd)")"':-}'; then
      if ${NOOP:+echo 1>&2 INFO $(pwd) }script/bootstrap; then
        eval export "_bootstrap_$(basename "$(pwd)")=1"
        source_profile || fl_error=1
        source_post || fl_error=1
      else
        fl_error=1
      fi
    fi
  fi

  return $fl_error
}

function bootstrap_in {
  local nm_project="$1"; shift

  pushd "$nm_project" 1>&-
  into_blockfile bootstrap
  bootstrap_block || fl_error=1
  popd 1>&-
}
