#!/usr/bin/env bash

function main {
  cat <<"__EOF"
#!/usr/bin/env bash

source "$APP_PATH/block/script/profile"

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"
  source "$shome/script/profile"
  require  
}

source sub "$BASH_SOURCE" "$@"
__EOF
}

source sub "$0" "$@"
