#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" || return 1

  main_clone "$@"
}

function main_clone {
  local tmp_list="$(mktemp -t XXXXXX)"

  if [[ "$#" == 0 ]]; then
    block list
  else
    echo "$@"
  fi > "$tmp_list"

  local git_block
  while read -r nm_block pth_block git_block end_block; do
    # Block has already been cloned
    if [[ -d "$pth_block" ]]; then
      continue
    fi

   # Block has not been cloned
    if [[ ! -d "$pth_block" ]]; then
      # Clone the repository
      git clone "$git_block" "$BLOCK_PATH/$nm_block"
      pth_block="$BLOCK_PATH/$nm_block"
    fi

    # If this isn't the top level block, recursively clone
    if [[ -z "$end_block" ]]; then
      pushd "$pth_block"
      main_clone
      popd
    fi

  done < "$tmp_list"
  rm -f "$tmp_list"
}

source sub "$0" "$@"
