#!/usr/bin/env bash

function upsert {
  if [[ -f "$1" ]]; then
    tee "$1"
  else
    cat > /dev/null
  fi
}

# ## Emit
function emit {
  echo '{ "require": [ "block", "cache", "service" ] }' | upsert Blockfile.json.site
  echo 'source ~/.bashrc' | upsert ~/.bash_profile
  echo 'source ~/work/block/script/profile ~' | upsert ~/.bashrc
}

emit "$@"
