#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  if [[ "$#" == 0 ]]; then
    return
  fi

  require
  eval "$@"
}

source sub "$0" "$@"
