#!/usr/bin/env bash

function main {
  cat <<"__EOF"
#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"
  
  source "$shome/script/rc"
}

profile
__EOF
}

source sub "$0" "$@"
