#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local url_dmg="$1"; shift
  local nm_volume=
  if [[ "$#" -gt 0 ]]; then
    nm_volume="$1"; shift
  fi
  local nm_package=
  if [[ "$#" -gt 0 ]]; then
    nm_package="$1"; shift
  fi

  if [[ -n "${DEBUG:-}" ]]; then
    set -x
  fi
  
  case "$(uname -s)" in
    Darwin)
      local fnm_dmg="$(basename "$url_dmg")"
      cache curl "$fnm_dmg" "$url_dmg" -sS -L
      hdiutil attach "${BASEBOX_CACHE}/curl/$fnm_dmg"
      if [[ -n "$nm_package" ]]; then
        block compile pkg "/Volumes/$nm_volume/$nm_package"
      fi
      if [[ -n "$nm_volume" ]]; then
        hdiutil detach "/Volumes/$nm_volume"
      fi
      ;;
  esac
}

source sub "$0" "$@"
