#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''
	source normalize

	local spec_block="$1"; shift

	local nm_user="$(echo "$spec_block" | cut -d/ -f1)"
	local nm_block="$(echo "$spec_block" | cut -d/ -f2)"
  if [[ "$nm_user" == "$spec_block" ]]; then
    nm_user="defn"
  fi

	cd "$BLOCK_PATH"
  mkdir -p "$nm_block"
  cd "$nm_block"
  git init
  hub create "$nm_user/"
  touch README.md
  git add README.md
  git commit -m 'initial commit'
  git push -u origin master
}

source sub "$0" "$@"
