#!/usr/bin/env bash

function require {
  local tmp_profile="$(mktemp -t XXXXXX)"

  local tmp_list="$(mktemp -t XXXXXX)"
  block list > "$tmp_list"

  while read -r nm_block pth_block git_block end_block; do
    if [[ ! -d "$pth_block" ]]; then
      echo "ERROR: missing $nm_block block" 1>&2
      set --
      break
    fi

    if [[ -e "$pth_block/script/profile" ]]; then
      echo "source $pth_block/script/profile"
    fi

  done < "$tmp_list" > "$tmp_profile"
  rm -f "$tmp_list"

  source "$tmp_profile"
  rm -f "$tmp_profile"
}

