#!/usr/bin/env bash

function block_bootstrap {
  if ! time script/bootstrap < /dev/null; then
    if [[ -x script/fresh ]]; then
      if ! script/fresh< /dev/null; then
        if [[ -x script/version ]]; then
          script/version
        fi
        return 1
      fi
    elif [[ -x script/stale ]]; then
      if script/stale < /dev/null; then
        if [[ -x script/version ]]; then
          script/version
        fi
        return 1
      fi
    fi
  fi
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  if [[ -n "${1:-}" ]]; then
    cd "${BLOCK_PATH}/$1"
    shift
  fi

  local tmp_list="$(mktemp -t XXXXXX)"
  block clone
  block list > "$tmp_list"

  while read -r nm_block pth_block git_block version_block end_block; do
    pushd "$pth_block"
    if [[ -x script/fresh ]]; then
      if ! script/fresh< /dev/null; then
        block_bootstrap
      fi
    elif [[ -x script/stale ]]; then
      if script/stale < /dev/null; then
        block_bootstrap
      fi
    elif [[ -x script/bootstrap ]]; then
      block_bootstrap
    fi

    if [[ -e script/profile ]]; then
      source script/profile
    fi

    popd
  done < "$tmp_list"
  rm -f "$tmp_list"
}

source sub "$0" "$@"
