#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  if [[ ! -x "script/version" ]]; then
    return 1
  fi

  if [[ "$(cat Blockfile.json | jq -r '.versions//{} | keys | length')" == 0 ]]; then
    return 1
  fi

  if diff <(script/version | jq -S .) <(block releases list | jq -S .); then
    return 1
  fi

  return 1
}

source sub "$0" "$@"
