#!/usr/bin/env bash

function main {
  local shome="${_block_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile" ''

	if [[ -x "$(which talign 2>/dev/null || true)" ]]; then
		if [ -t 1 ] ; then
			talign
		else
			cat
		fi
	else
		cat
	fi
}

source sub "$0" "$@"
