#!/usr/bin/env bash

function git_stuff {
  # initialize new ssh hosts
  rm -f ~/.ssh/known_hosts
  ssh -oStrictHostKeyChecking=no github.com true &
  ssh -oStrictHostKeyChecking=no bitbucket.org true &
  ssh -oStrictHostKeyChecking=no localhost true &
  wait
}

function home_stuff {
  local git_home="$1"; shift

  # clone home
  if [[ ! -d .git ]]; then
    git clone "$git_home" home
    mv home/.git . || rm -rf home/.git
    git reset --hard
    git clean -fd
  else
    git reset --hard
  fi
  
  git pull

  set +x; source script/ciprofile; set -x
}

function block_stuff {
  : ${BLOCK_PATH:="$(pwd)/work"}
  export BLOCK_PATH

  # bootstrap block
  git clone git@github.com:defn/block "$BLOCK_PATH/block" || true
  pushd "$BLOCK_PATH/block"
  git pull
  set +x; source script/profile; require; set -x
  block clone
  block bootstrap
  set +x; source script/profile; require; set -x
  popd
}

function cache_stuff {
  export BASEBOX_CACHE="/vagrant"

  if [[ ! -d "$BASEBOX_CACHE" ]]; then
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/cache"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/box"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/distfiles"
    sudo install -d -o ubuntu -g ubuntu -m 0755  "$BASEBOX_CACHE/packages"
  fi

  case "$(uname -s)" in
    Linux)
      {
        echo "Acquire::Languages { \"en\"; };"
        echo "Acquire::http { Pipeline-Depth \"200\"; }"
      } | sudo tee /etc/apt/apt.conf.d/99boxcache

      if [[ -n "${http_proxy:-}" ]]; then
        {
          echo "Acquire::http::Proxy \"$http_proxy\";"
        } | sudo tee -a /etc/apt/apt.conf.d/99boxcache
      fi
      ;;
  esac
}

function update_stuff {
  case "$(uname -s)" in
    Linux)
      sudo aptitude upgrade -y
      ;;
    Darwin)
      sudo softwareupdate -i -v -a
      ;;
  esac

  facts cache
}

function main {
  # setup
  local nm_repo=

  if [[ "$#" == 0 ]]; then
    if [[ ! -d ".git" ]]; then
      echo "ERROR: specify a git repository to build" 1>&2
      return 1
    fi
  else
    nm_repo="$1"; shift
  fi

  if [[ -n "${1:-}" ]]; then
    export http_proxy="$1"; shift
    export https_proxy="$http_proxy"
    export ftp_proxy="$http_proxy"
  fi

  if [[ -n "${1:-}" ]]; then
    export ssh_proxy="$1"; shift
  fi

  case "$(uname -s)" in
    Linux)
      sudo aptitude update
      sudo aptitude -y install git vim unzip curl language-pack-en lvm2 # mirror basebox-ubuntu/site.sh
      ;;
  esac

  # setup
  cache_stuff
  git_stuff
  home_stuff "$nm_repo"
  block_stuff

  # bootstrap dependencies
  block clone
  block runmany 8 'cd $1 && git pull' || true
  block bootstrap

  # fully source home
  set +x; require; set -x

  # update packages
  update_stuff

  # cleanup
  case "$(uname -s)" in
    Linux)
      sudo rm -f /etc/apt/apt.conf.d/99boxcache
      ;;
  esac
}

set -exfu
exec 2>&1
cd
main "$@"
