#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" || return 1
  source "block_require"

  require

  if [[ "$#" -gt 0 ]]; then
    eval "$@"
  fi
}

source sub "$0" "$@"
