#!/usr/bin/env bash

function main {
  cat <<"__EOF"
  local shome="${_block_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
__EOF
}

source sub "$BASH_SOURCE" "$@"
