#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  if [[ ! -x "script/version" ]]; then
    return 1
  fi

  if diff <(script/version | jq -S .) <(block releases | jq -S .); then
    return 1
  fi

  return 1
}

source sub "$0" "$@"
