#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block list | runmany 1 3 '[[ -z "${2:-}" ]] && exit; echo $1 $2 $3 $(cd $2 && git rev-parse HEAD) $(cd $2 && git rev-parse --abbrev-ref HEAD)' | \
    if [[ -x "$(which talign 2>/dev/null || true)" ]]; then
      if [ -t 1 ] ; then
        talign
      else
        cat
      fi
    else
      cat
    fi
}

source sub "$0" "$@"
