#!/usr/bin/env bash

function main {
  local shome="${_block_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile" ''

  diff -wb Blockfile.lock <(block lock show) | block align
}

source sub "$0" "$@"
