#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  if [[ "$#" == 0 ]]; then
    set -- .
  fi

  runmany 4 'cd "$1" && block stale cmd' "$@"
}

source sub "$0" "$@"
