#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block list | grep -v '\.$' | runmany 1 3 'echo $1 $2 $3 $(cd $2 && git rev-parse HEAD) $(cd $2 && git rev-parse --abbrev-ref HEAD)' | block align
}

source sub "$0" "$@"
