#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" || return 1
  source "block_list"

  block_list "$@"
}

source sub "$0" "$@"

