#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  cat Blockfile.lock | perl -pe 's{\$\{BLOCK_PATH\}}{'"$BLOCK_PATH"'}' \
    | runmany 4 5 'cd "$2" && git pull'
}

source sub "$0" "$@"
