#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  export nm_branch="$(cat Blockfile.json | jq -r '.blocks//""')"
  if [[ -z "$nm_branch" ]]; then
    nm_branch="$(git rev-parse --abbrev-ref HEAD)"
    local sha_branch="$(git rev-parse HEAD)"
    if [[ "$nm_branch" == "$sha_branch" ]]; then
      nm_branch=''
    fi
  fi

  main_clone "$@"
}

function main_clone {
  local tmp_list="$(mktemp -t XXXXXX)"

  if [[ "$#" == 0 ]]; then
    block list
  else
    echo "$@"
  fi > "$tmp_list"

  local git_block
  while read -r nm_block pth_block git_block version_block end_block; do
    # Block has already been cloned
    if [[ -d "$pth_block" ]]; then
      continue
    fi

    # Block has not been cloned
    rmdir "$pth_block" 2>/dev/null || true
    if [[ ! -d "$pth_block" ]]; then
      # Clone the repository
      local nm_work="${nm_block##*/}"
      git clone ${GIT_CC_REMOTE:+-o "${GIT_CC_REMOTE}"} ${nm_branch:+-b "$nm_branch"} "$git_block" "$pth_block"
      pushd "$pth_block" >/dev/null
      if [[ -n "$version_block" ]]; then
        git checkout "$version_block"
      fi
      popd >/dev/null
    fi

    # If this isn't the top level block, recursively clone
    if [[ -z "$end_block" ]]; then
      pushd "$pth_block"
      main_clone
      popd
    fi

  done < "$tmp_list"
  rm -f "$tmp_list"
}

export CALLING_PWD="${CALLING_PWD:-$PWD}"
source sub "$0" "$@"
