#!/usr/bin/env bash

function setup_submodules {
  if ! git submodule update --init --remote --no-fetch -j 10; then
    git submodule update --init
  fi
}

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  setup_submodules
}

source sub "$0" "$@"


