#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  cat Blockfile.lock | perl -pe 's{\$\{BLOCK_PATH\}}{'$ENV["BLOCK_PATH"]'}' \
    | runmany 4 5 'set -e; if [[ ! -d "$2" ]]; then git clone -b "$5" "$3" "$2"; fi; cd "$2"; if ! git merge-base "$4" "$4" ; then git fetch; fi; git checkout -B "$5" "$4"'
  block lock diff
}

source sub "$0" "$@"
