#!/usr/bin/env bash

function main {
  cat <<"__EOF"
#!/usr/bin/env bash

function profile {
  local shome="${_block_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
}

profile
__EOF
}

source sub "$0" "$@"
