#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''

  diff -wb Blockfile.lock <(block lock show) | talign
}

source sub "$0" "$@"
