#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  curl -sL -L -o "$shome/exec/shflags" https://raw.githubusercontent.com/nvie/shFlags/master/src/shflags

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y ruby gettext
      ;;
  esac

  block clone
}

main "$@"
