#!/usr/bin/env bash

# The `cibuild` script can bootstrap Block and optional blocks.

# ## Suggested usage:

#     mkdir ~/work
#     cd ~/work
#     git clone git@github.com:defn/block
#
#     cd ~/work/block
#     script/cibuild git@github.com:defn/home

# ## Main

#
function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  # Source Block's profile to get access to `block` commands
  source "$shome/script/profile" ''
  
  setup_block

  setup_optional
}


# ## Setup Block

#
function setup_block {
  # Bootstrap & require Block to get access to dependencies
  pushd "$shome"
  block bootstrap
  require
  popd
}

# ## Bootstrap optional blocks

#
function setup_optional {
  local git_block
  for git_block in "$@"; do
    if [[ ! -d "$git_block" ]]; then
      # Clone the block if it isn't there
      cd "$BLOCK_PATH" >/dev/null
      git clone "$git_block" || true
      git_block="$BLOCK_PATH/$(basename "$git_block")"
    fi

    # For each block:
    cd "$git_block"

    # - clone dependencies
    block clone

    # - build dependencies
    block bootstrap 

    # - source dependencies
    require
  done
}

main "$@"
