#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" ''
  
  pushd "$shome"
  block bootstrap
  require
  popd

  local git_block
  for git_block in "$@"; do
    if [[ -d "$git_block" ]]; then
      pushd "$git_block" >/dev/null
      block lock sync
    else
      pushd "$BLOCK_PATH" >/dev/null
      git clone "$git_block" || true
      popd >/dev/null

      pushd "$BLOCK_PATH/$(basename "$git_block")" >/dev/null
      git fetch
      git reset --hard origin/master
    fi

    block bootstrap 
    require
    popd >/dev/null
  done
}

main "$@"
