#!/usr/bin/env bash

function debug {
  if [[ -n "${DEBUG:-}" ]]; then
    if "$@"; then
      true
    fi
  fi
}

function sub_profile {
  source "$shome/vendor/sub/script/profile"
}

function profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  local cmd_sub="$(type -P sub || true 2>&-)"
  if [[ ! -x "$cmd_sub" ]]; then
    if [[ -r "$shome/vendor/sub/script/profile" ]]; then
      sub_profile
    fi
  fi
}

function source_profile {
  local pth_profiled
  for pth_profiled in $(set +f; ls -d .profile.d/*.sh 2>&- || true); do
    if [[ -f "$pth_profiled" ]]; then
      debug echo INFO "$(pwd)/$pth_profiled" 1>&2
      source "$pth_profiled"
    fi
  done

  if [[ -r "script/"profile ]]; then
    debug echo INFO "$(pwd)/script/profile" 1>&2
    source "script/profile"
  else
    echo "WARNING: script/profile not found in $(pwd)" 1>&2
  fi
}

function req_blockfile {
  if [[ -f "Blockfile" ]]; then
    local nm_block
    for nm_block in $(cat "Blockfile" | yq -r '[.require[] | [.] | flatten] | flatten[]'); do
      if require "$nm_block"; then
        true
      fi
    done
  fi

  return 1
}

function require {
  local fl_error=0

  local nm_project
  for nm_project in "$@"; do
    if [[ -d "/$nm_project" ]]; then
      pushd "/$nm_project" 1>&-
      req_blockfile
      source_profile || fl_error=1
      popd 1>&-
    elif [[ -d "./$nm_project" ]]; then
      pushd "./$nm_project" 1>&-
      req_blockfile
      source_profile || fl_error=1
      popd 1>&-
    elif [[ -n "${APP_PATH:-}" ]]; then
      local pth_app
      for pth_app in $(echo "${APP_PATH}" | tr ':' " "); do
        if [[ -d "$pth_app/$nm_project" ]]; then
          pushd "$pth_app/$nm_project" 1>&-
          req_blockfile
          source_profile || fl_error=1
          popd 1>&-
          break
        fi
      done
    fi
  done

  if [[ "$#" == 0 ]]; then
    req_blockfile
    source_profile || fl_error=1
  fi

  return $fl_error
}

profile
