#!/usr/bin/env bash

function sub_profile {
  source "$shome/vendor/sub/script/profile"
}

function profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  local cmd_sub="$(type -P sub || true 2>&-)"
  if [[ ! -x "$cmd_sub" ]]; then
    if [[ -r "$shome/vendor/sub/script/profile" ]]; then
      sub_profile
    fi
  fi
}

profile
