#!/usr/bin/env bash

function mark_source {
  local pth_profile="$1"; shift
  debug echo INFO "$pth_profile" 1>&2
}

function source_pre {
  local pth_profiled
  set +f
  for pth_profiled in .profile.d/*.pre; do
    set -f
    if [[ -f "$pth_profiled" ]]; then
      mark_source "$PWD/$pth_profiled"
      source "$pth_profiled"
    fi
  done
}

function source_profile {
  local nm_block="${PWD##*/}"
  if [[ -f .app-name ]]; then
    read nm_block < .app-name
  fi

  local a="_require_${nm_block//-/_}"
  if [[ -r "script/profile" ]]; then
    if [[ -z "${!a:-}" ]]; then
      mark_source "$PWD/script/profile"
      eval "$a=1"
      source "script/profile"
    fi
  else
    echo "WARNING: script/profile not found in $PWD" 1>&2
  fi

  if [[ -r "script/rc" ]]; then
    source "script/rc"
  fi
}

function source_post {
  local pth_profiled
  set +f
  for pth_profiled in .profile.d/*.post; do
    set -f
    if [[ -f "$pth_profiled" ]]; then
      mark_source "$PWD/$pth_profiled"
      source "$pth_profiled"
    fi
  done
}

function require_in {
  local nm_project="$1"; shift

  pushd "$nm_project" >/dev/null
  source_pre || fl_error=1
  into_blockfile require
  source_profile || fl_error=1
  source_post || fl_error=1
  popd >/dev/null
}

function require {
  block_walker "$FUNCNAME" "$@"
}
