#!/usr/bin/env bash

function stale {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -f "$shome/exec/shflags" ]]; then
    if [[ -x "$(which ruby 2>/dev/null || true)" ]]; then
      if [[ -x "$(which envsubst 2>/dev/null || true)" ]]; then
        return 1
      fi
    fi
  fi

  return 0
}

stale "$@"
