#!/usr/bin/env bash

function stale {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -f "$shome/exec/shflags" ]]; then
    return 1
  fi

  return 0
}

stale "$@"
